name: deploy to production

on:
  push:
    branches:
      - main

jobs:
  update-production:
    runs-on: self-hosted

    steps:
      - name: pull latest changes
        run: git pull origin main
        working-directory: /opt/test

      - name: install dependencies
        run: npm install
        working-directory: /opt/test

      - name: restart application
        run: pm2 restart all